raptorjit/raptorjit

.gitmodules, .travis.yml
Just now only 507/508 tests are executed. Test 366 fails. This also happens with LuaJIT v2.1. I need to check that with upstream on the test suite.
=> Add LuaJIT test suite as submodule & integrate with Travis-CI

.gitmodules, .travis.yml
... and cherry-pick a fix to make all tests run.
This fork is due to my uncertainty about how the upstream community for the test suite works (LuaJIT/LuaJIT-test-cleanup#11) and the fact that right now the latest version of LuaJIT v2.1 fails the latest version of the test suite.
=> Fork LuaJIT-test-cleanup to raptorjit-testsuite

.travis.yml, README.md, default.nix, src/Makefile
Formalize the build-time dependencies in `default.nix`. Requires `clang` as the host C compiler and `luajit` as the bootstrap Lua interpreter (for DynASM etc.) README is updated with instructions for setting up the build environment automatically using `nix`.
Resolves #23 #24 #25.
=> Define build environment using nix

README.md, src/ifdef-defile, src/lj_arch.h, src/lj_err.c, src/lj_frame.h, src/vm_x64.dasc
I hope that I understand this feature correctly... it's for allowing C++ exceptions to propagate through LuaJIT? (e.g. C++ calls LuaJIT calls C++ throws exception?)
Removing with this rationale:
- Complex hairy code.
- Limited value.
- Looks straightforward to re-introduce if needed.
=> Define NO_UNWIND

README.md
Taking a fairly radical approach of only supporting the latest Intel Core CPUs (Haswell/Skylake) & removing any optimizations that don't help those specific CPUs.
=> README: Declared CPU & Optimization policy

src/vm_x64.dasc
Remove code protected by preprocessor directives that are false. (Doing the same job of 'unifdef' but on DynASM preprocessor syntax.)
Overall code reduction of `vm_x64.dasc` from LuaJIT is now ~20%. This is significant because much of the removed code was in ifdefs scattered throughout the file. I find that kind of code very hard to follow and maintain.
=> vm_x64.dasc: Resolve +JIT +FFI -X64WIN

src/lj_asm_x86.h
Fix typo `s/IR_KPTR/IR_KKPTR/` bug in b1cfd2730e42d8a0b8d5f76f0c05dac948925dec affecting constant pointers to constant values.
Thanks @jaens for catching this at https://github.com/raptorjit/raptorjit/pull/47#commitcomment-21392114.
=> Fix IR_KKPTR case of #47

src/lj_asm_x86.h
Remove a special case from the assembler that generates "Slow LEA"
instructions that can execute poorly on Skylake and Haswell CPUs.
The "slow LEA" is one that uses base+index+offset operands. These
instructions "have increased latency and reduced dispatch port choices
compared to other LEAs."
Links:
- https://software.intel.com/en-us/node/544484
- http://stackoverflow.com/questions/21288214/what-are-fast-lea-and-slow-lea-unit-in-the-microarchitecture-of-intes-cpu
Resolves RaptorJIT/RaptorJIT#54.
Here is an example of a "slow LEA" instruction that was emitted before:
lea eax, [rbx+rdx+1234]
The new replacement avoids the bad case:
lea eax, [rbx+1234]
add rax, rdx
On Haswell and Skylake CPUs this improves the md5 benchmark
performance by ~15%. The difference in cycles (time) correlates …
=> md5 benchmark 15% speedup by removing "slow LEA"

src/Makefile, src/lib_jit.c, src/lj_gc.c, src/lj_obj.h, src/lj_vmprofile.c, src/lj_vmprofile.h, src/luajit.h
Port the "VMProfile" sampling profiler from the Snabb branch of LuaJIT.
This is a trace-oriented sampling profiler. For each trace it counts the time spent in the trace head, the trace loop, FFI calls, and the GC. It also counts the total time spent in the JIT and interpreter.
See https://github.com/LuaJIT/LuaJIT/pull/290 and https://github.com/snabbco/snabb/pull/1125.
=> Port VMProfile sampling profiler from Snabb

src/lib_jit.c, src/lj_vmprofile.c, src/luajit.h, testsuite/test/index, testsuite/test/raptorjit/index, testsuite/test/raptorjit/vmprofile.lua
Extend the "Lua C API" for vmprofile to support allocating multiple
profiles and switching between them. This makes it easier to use.
Previously the expectation was that this functionality would be
implemented in Lua code using ljsyscall to allocate file-backed shared
memory for profiles and then the FFI to switch between them. (This is
still possible, too, and it works the same as it did before.)
Added test coverage to the test suite.
=> vmprofile: Extend Lua API and add test cases

Makefile
This makes the build work like it says in the README. (Otherwise you need to `cd` into `src/` to run `make reusevm`.)
=> Makefile: Added reusevm target at top-level

src/lj_asm_x86.h
https://github.com/LuaJIT/LuaJIT/commit/78f5f1ce fixed emit_loadk64, but
overlooked asm_fuseloadk64.
Contributed by Peter Cawley.
=> x64/LJ_GC64: Fix asm_fuseloadk64()

src/lj_trace.c
Remove unused feature where the trace number at exit is discovered with a linear search for the trace whose mcode includes the exit jump.
This is not used on the x86-64 VM because the trace number is already known without having to search.
(Seems like the LuaJIT ARM VM needs to randomly access O(n) GCtrace cache lines to return to the interpreter, for a VM with n traces. Seems weird because the assembler code handling trace exit already had the answer in the `vmstate` structure just a few instructions earlier? Anyway, this is not something that happens in RaptorJIT.)
=> Remove EXITSTATE_PCREG

src/lj_ir.c, src/lj_iropt.h, src/lj_jit.h, src/lj_opt_loop.c, src/lj_snap.c, src/lj_snap.h, src/lj_state.c, src/lj_trace.c
If we only need a few ~64K element arrays then just allocate those up front and don't worry about dynamically growing things. This is simpler, requires less code, and has no obvious practical downside.
Resolves #128.
=> Statically allocate JIT temp buffers

src/lj_trace.c
Resolve #125 by clearing all bytecode blacklistings when `jit.flush()` is called.
Code is written and tested by @alexandergall and here is his original comment on the commit:
> The blacklist is cleared by going through all prototype objects on the heap marked to contain patched bytecodes and revert all instances of `IFUNCF`, `IFORL`, `IITERL` and `ILOOP`.
The cost should be comparable to a full garbage collection, which seems acceptable in the context of `jit.flush()` that already does expensive work like re-tracing every function and regenerating all machine code. (If the traversal would ever become a practical performance issue then we could address this a simple index of some kind.)
(cherry picked from commit https://github.com/alexandergall/snabbswitch/commit/8beb311332a6c95ab1d2934f29 …
=> lj_trace.c: unpatch blacklisted bytecodes when flushing traces

src/lj_jit.h, src/lj_record.c, src/lj_state.c
This is a work-in-progress branch to log each bytecode that is recorded for a trace.
The basic intention is to include the recorded bytecodes for each trace in the auditlog (#63). Then the tools can show the bytecodes for each trace (like LuaJIT `-jdump=b`) and even show which lines of source code were executed (via debug info mapping from bytecode to source.)
Open question: Can the bytecode log be copied from jit_State to GCtrace when a trace is completed? This would depend on the `GCproto*` pointers staying valid so we either need to be sure that each prototype referenced in the log is also referenced as a constant in the trace IR (I think so...?) or we need to teach the GC to traverse the log to keep the references alive.
=> [wip] Add log of recorded bytecodes (BCLogRec) to jit_State

src/lj_bcread.c, src/lj_debug.c, src/lj_obj.h, src/lj_parse.c
The source code line number of each bytecode is now always stored in
memory as a 32-bit number.
Previously a simple compression scheme was used: an 8-bit number was
used for <256 line functions, a 16-bit number for <64K line functions,
and a 32-bit number otherwise.
This specific optimization is not appropraite for RaptorJIT. On the
one hand there will never be a practical benefit on any server
platform because the amount of memory involved is miniscule, and on
the other hand it complicates the JIT data structures that need to be
understood by new maintainers and also supported in external tools
like [Studio](http://github.com/studio/studio).
(Studio needs to understand the RaptorJIT data structures and in this
case I decided to do that by removing code from RaptorJIT rather than
adding …
=> Remove feature to compress GCproto.lineinfo

check-generated-code.nix, src/lj_jit.h, src/lj_trace.c
For debugging purposes it is very useful to be able to refer to the origin of a trace (parent/exit) and so this change stores that information persistently in `GCtrace` instead of only ephemerally in `jit_State`.
These fields are now duplicated in `jit_State` (valid while recording) and `GCtrace` (valid after recording.) This duplication could be avoided by putting them only in `GCtrace` and accessing them via `J->cur` but this would be a more noisy change since the existing fields are accessed from many places including DynASM macros.
=> GCtrace: Record origin of trace (parent & exitno)

src/lj_asm.c, src/lj_jit.h
Add a `szirmcode` array to GCtrace that keeps track of how many bytes of machine code were assembled for each IR instruction.
This allows us to construct an association between IR code and mcode, either to see the mcode that was assembled for a given IR instruction, or to map a machine code instruction back to the relevant IR instruction.
Resolves the desire to be able to relate IR code and mcode expressed over at https://github.com/raptorjit/raptorjit/pull/63#issuecomment-309700685. cc @javierguerragiraldez.
=> GCtrace: Make it possible to map between IR and mcode insns

src/lj_jit.h, src/lj_record.c, src/lj_trace.c
This branch contains some experimental changes for making the JIT blacklist bytecodes more conservatively (#100):
- f7212ccb97ea39effb9c311b5a7affc8f66d3bf2: Clear the penalty cache after each successful trace (we only want to blacklist bytecodes that abort many times **in a row**.)
- 01dc8448637f80151fa8de4ede765ff81efe7536: Increase `HOTCOUNT_MAX` to allow more trace attempts before blacklisting. (This can probably be rewritten better.)
- a720595aed834541f61ad1edfb75ac8c45a4c5dd: Reset HOTCOUNT table after JIT flush. This is intended to address a situation where the JIT chooses an extremely sub-optimal set of traces after a flush, but for some reason I don't think it is actually effective.
- ce6fbb4240fa3d626b6a1eb8ddafd3d36b335751: Relax heuristic for root trace meeting JIT loop. If …
=> JIT heuristic updates for stable performance [experimental]

src/lj_record.c
Record calls to blacklisted functions the same way as calls to uncompiled functions. This allows for the possibility that a blacklisted function can be successfully recorded as part of a larger trace.
If the function truly cannot be compiled into other traces then it will continue to abort and lead to more blacklistings, at the cost of some extra "due diligence" by the JIT to avoid false-negatives. This is perfectly in line with the RaptorJIT goal of blacklisting code conservatively and taking pains to find successful traces.
This change does not affect the treatment blacklisted loops. Those may or may not deserve further consideration.
Resolves raptorjit/raptorjit#119.
=> lj_record.c: Record IFUNC/IFUNCV the same as FUNC/FUNCV

src/lj_obj.h
Simplify the definitions of `MRef` and `GCRef` by making them pointers rather than structures wrapping 64-bit uint address values.
The struct definitions were an artefact inherited from LuaJIT, which supports having different pointer sizes for the Lua heap vs the process address space. This is redundant in RaptorJIT where pointers are always 64-bit (i.e. because we have standardized on GC64 mode from LuaJIT.)
This is partly motivated by reducing noise when browsing C objects in a debugger.
Resolves #130.
=> Redefine MRef and GCRef as pointer types

src/lj_vmprofile.c, src/lj_vmprofile.h, src/luajit.c
Now it is possible to enable VMProfile trace profiling to a file from the command line.
=> Add '-p file' command line syntax for VMProfile

testsuite/bench/default.nix
The awk code for extracting the instructions and cycles counts from the perf output was not working. Likely I had updated perf to an incompatible version and pushed that without testing. Naughty me.
This change was made while live coding on http://twitch.tv/lukegorrie :).
=> testsuite/bench: Fix awk parsing of perf output

src/lj_str.c
Make `lj_str_new()` faster and more consistent by removing its "fast-path" special case.
The "fast-path" was bad because:
- It's a tricky custom memcmp routine that needs to be maintained.
- It is actually *slower* than the slow-path (builtin memcmp) on modern Linux/x86.
- The special casing could cause confusing performance in practice e.g. a totally unrelated memory allocation could bias an important buffer towards the fast-path or the slow-path and impact overall application performance.
The fast-path code was written in 2010 and a lot has happened since then e.g. many revisions of the CPU string instructions and GCC code and glibc code and so on. I think the optimization had simply bit-rotted.
Here is a [benchmark report](https://hydra.snabb.co/build/2920065/download/3/bench-jitter.png …
=> lj_str.c: Remove special-case string interning fast-path

src/lib_jit.c, src/lj_vmprofile.c, src/luajit.c, src/luajit.h
Make simple usage of VMProfile more convenient.
For example:
jit.vmprofile.open("bigloop")   for i = 1, 1e9 do end
jit.vmprofile.open("shortloop") for i = 1, 1e6 do end
This involves two changes to the jit.vmprofile API:
Preload the jit.vmprofile library, so that no require() is needed.
Make the default behavior of jit.vmprofile.open(filename) include
selecting the profile and enabling the timer. This way a single call
with a filename will enable live profiling to disk.
The slightly awkward aspect is that the jit.vmprofile.open() changes
are not quite backwards compatible. The old behavior was to not select
the new profile nor enable the timer (on the assumption that this will
be done separately.) This behavior can be accessed using new optional
arguments boolean arguments `noselect` and …
=> Support "one-liner" usage of jit.vmprofile.open()

src/lj_debug.c, src/lj_parse.c
Remove two clever tricks whose benefits don't justify their complexity:
1. The GCproto.lineinfo table used to exclude the first and last bytecodes. The line numbers of those bytecodes had to be calculated as a special case (using other state in the GCproto struct.) Now every bytecode has an entry in the lineinfo table and is treated the same.
2. The GCproto.lineinfo table used to store delta values relative to the first line. Now the absolute line number is stored. (The deltas helped with a compression scheme that has previously been removed from RaptorJIT.)
Remove the `#ifdef` option to build the VM without linenumber debug support too. RaptorJIT does not want this kind of feature parameterized with `#ifdef` in the VM code.
=> lj_parse.c, lj_debug.c: Remove clever tricks in lineinfo encoding

README.md, raptorjit.nix, src/Makefile
It was a bit of a flight of fancy to use a pinned version of clang.
This would make sense if we were really depending on hyper-specific behaviour of the C compiler, like some automatic SIMD parallization, but in reality we're not. So don't be fussy and just keep it simple.
=> Just use the default gcc instead of clang 4.0.0.

shell.nix
The README says that running 'nix-shell' should open a RaptorJIT build environment. The command actually needed was 'nix-shell -A raptorjit'. However, adding this shell.nix file makes 'nix-shell' do the right thing.
Resolves #158.
=> shell.nix: Make 'nix-shell' command work as documented

README.md
RaptorJIT currently only supports Linux and x86-64. This was not explicitly stated in the README which caused problems such as #161.
=> README.md: State more clearly that Linux is required

src/lj_vmprofile.c
This is a fix by @takikawa cherry-picked from the Snabb branch of RaptorJIT. It switches VMProfile from sampling based on wall-clock time to sampling based on userspace-CPU-time. This prevents profiler signals from interrupting system calls and it also keeps the profiler data focused on time spent in RaptorJIT code itself. (When you are concerned about time spent in system calls then it is better to use a separate system profiler like `perf`.)
----
Avoids infinite looping due to system call restarts triggered by SIGPROF handling.
Virtual time doesn't account for time spent in the kernel handling system calls but Snabb tries to avoid spending time in system calls.
(cherry picked from commit c4681a6c59f705fc49368bc1ae8fdc3fbbeee685)
=> Use virtual instead of profile time for vmprofile

src/lj_trace.c
Make JIT trace numbers unique for completed traces. This way a trace
number is an unambiguous way to refer to a GCtrace object even across
flushes over the JIT.
The immediate motivation is to make the vmprofile data valid across
JIT flushes. It is counting samples by trace number and so when trace
numbers are reused then multiple traces can "collide" on the same
profiler counter.
=> lj_trace.c: Make trace numbers unique (stop reusing them)

src/Makefile, src/host/buildvm.c, src/jit/bc.lua, src/jit/bcsave.lua, src/luajit.c, src/luajit.h
Make obvious printouts declare the project to be "RaptorJIT 1.0.0" rather than "LuaJIT 2.1.0".
Remove copyright printout on startup. It's hard to do justice to the full story in so few characters.
=> Minimal rebranding from LuaJIT -> RaptorJIT

src/lj_asm.c, src/lj_trace.c
This array was allocated too large (padded to REF_BASE) and was not freed.
This branch crashes with segfault on the `fasta` benchmark but I am not sure if this is a consequence of this change yet.
=> Fix allocation/deallocation of T->szirmcode

src/lj_ctype.c
This is a potential fix for #180 where trying to print certain ctypes puts the runtime system into an infinite loop.
I do not honestly understand the phenomenon of ctypes being "not OK" for printing (`ct->ok=0`) and so for the moment I am only adding some defensive programming to try and ensure that these types print as `?` instead of causing undefined behaviour like crashes and hangs.
=> lj_ctype.c: Detect loops in ctype_repr()

src/lj_jit.h, src/lj_state.c, src/lj_trace.c
The `J->trace` array is now statically allocated with its maximum size (512KB) rather than being dynamically growth with reallocation.
`jit_flushall()` now correctly resets the counter for the `JIT_P_maxtraces` limit on traces created before an automatic flush.
=> lj_trace.c: Fix and simplify allocation of J->trace

default.nix, src/Makefile
The standard test cases are all executed with VMs build with `-DLUA_USE_ASSERT`. If the check argument is specified then the VM is also built with `-Werror` to check for (fail on) compiler warnings.
=> default.nix: Test with -DLUA_USE_ASSERT and -Werror

src/lj_asm.c, src/lj_auditlog.c, src/lj_jit.h, src/lj_state.c, src/lj_trace.c
Fix a memory leak in trace debug information. Re-enable the assertion that automatically "balances the books" to detect memory leaks by comparing bytes allocated to bytes freed.
Resolves #185.
=> Reinstate memory leak protection & make it work

src/lj_ctype.c
Fixes an obscure assertion failure that can occur when logging ctype names to the auditlog (when RaptorJIT is compiled with LUA_USE_ASSERT.)
=> lj_ctype.c: Detect bad ctypeid without failing lua_assert

PROFESSIONAL-SUPPORT.md
RaptorJIT users need to know that there is professional support available if and when they need it. This is to reduce the risks associated with starting new projects (e.g. missing deadlines due to learning curve) and to reduce the costs of maintaining these applications (e.g. having in-house JIT internals gurus who need to be hired/trained/retained/replaced/etc over time.)
Having a set of service providers of diverse capacity/speciality/locale would be a major positive for the project so please don't be shy about adding your name to the list (person or company, in alphabetical order) if you want people to consider contacting you when they are looking for support.
cc @wingo @eugeneia @fsfod @agladysh @corsix.
=> Add PROFESSIONAL-SUPPORT.md list of service providers

src/Makefile
Fix a bug where lj_dwarf_dwo_dyn.o was built as a shared object and caused linkage problems for libraptorjit.so.
Hopefully resolves #216.
=> src/Makefile: Fix unwanted dynamic linkage of dwarf debug info

src/lj_str.c
Merge luajit/luajit#243 into RaptorJIT.
This change makes an explicit comparison of the hash value when comparing strings for the purposes of interning. This takes additional relevant information into account since the strings being searched are only known to have a partial hash value match.
=> Compare hash value when interning strings

src/lj_ir.h, src/lj_snap.c, testsuite/test/trace/index, testsuite/test/trace/unsink.lua
Fix a bug where 64-bit pointer values would be mangled during unsinking. The unsinking code was not using the correct layout for GC64 IR constants (value in adjacent slot) for this case.
Fixed in an intense debugging session together with @thibaultcha and @dndx.
This branch includes the test from #245 and makes it pass.
=> Fix unsinking of 64-bit pointers 

testsuite/test/trace/index, testsuite/test/trace/unsink.lua
This PR adds a test case for the root problem causing a segfault at https://github.com/openresty/lua-resty-core/issues/232. The issue affects both LuaJIT and RaptorJIT specifically in GC64 mode.
Fix to follow immediately.
=> testsuite: Add (segfaulting) test for allocation unsinking

src/Makefile, src/Makefile.dep, src/lib_aux.c, src/lj_alloc.c, src/lj_alloc.h, src/lj_state.c, src/lj_state.h
This reverts commit b060b48c62f937e9f0ffe97b351e80ff6c4843a2.
After some detective work we found that this change was actually responsible for the performance regression we observed. In hindsight it makes perfect sense, as relying on system malloc involves more syscalls than the userspace dlmalloc implementation.
Supersedes #267
=> Revert "Remove built-in dlmalloc"
